### ISSUE TITLE
Sound noisy and can’t listen to TJBot 

### ISSUE THREAD

**Issue by ricar61** [jweisz/tjbot-playground#3]
When I turn on the TJBot and play a wav file using aplay it works perfectly. When I start de TJBot-daemon, there is a constant noise on the speaker and cannot listen to the message created by playground.

**Comment by ricar61** [comment]
additional info: reboot RaspberryPi 3, go to test folder under tjbot, sudo node test.play.js, works OK, plays the sound correctly. When run the sudo node tjbot-daemon on Desktop directory, no sound, only noise..... need help please.. any suggestion ?

**Comment by vkjuju** [comment]
I hit the same thing , any advice ?

**Comment by jweisz** [comment]
I haven't been able to reproduce this. My best advice is to use a USB soundcard instead of the analog sound jack, I've had nothing but problems with the RPi sound jack interfering with the LED.

**Comment by vkjuju** [comment]
yes, usb soundcard works around this issue, Thanks
