### ISSUE TITLE
Links to watson services do not resolve

### ISSUE THREAD

**Issue by jurijpar** [jweisz/tjbot-playground#7]
The README contains this section IBM Watson services such as Speech to Text, Visual Recognition, Language Translator, and more!

Unfortunately those links such as https://www.ibm.com/watson/developercloud/speech-to-text.html  throw errors. The current links are https://www.ibm.com/watson/services/speech-to-text/ etc.

**Comment by jweisz** [comment]
Thanks! Just fixed the broken links in the README.
